### ISSUE TITLE
Add functional tests.

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sacro#100]
We should add functional tests that can interact with a rendered page and click on things that speak to an actual server.

This is Not Trivial, and I don't think we currently do this in any other of our projects.  It presumably involves selenium or modern equivalent.

**Comment by madwort** [comment]
some tests added in https://github.com/opensafely-core/sacro/pull/119 - not currently running in CI or in `just test`, and apprently broken right now.
