### ISSUE TITLE
Integrate big ACRO PR

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#108]
There is a big ACRO PR coming [here](https://github.com/AI-SDC/ACRO/pull/89).

Changes in that PR include:

* Splitting multi-table outputs over multiple files.
* Removing timestamps from file names and putting them in the JSON.
* Overhauling the JSON structure.
* Copying custom outputs into the directory.
* Referring to the outputs by relative file paths.
* Adding status and output type properties.

Once this PR has landed we need to integrate the new formats etc with the viewer. We shouldn't try to take advantage of all the new stuff (e.g. the output type which is now available) -- there are further issues coming to cover that.

For now we'll just display the first file for multi-file outputs.

**Comment by bloodearnest** [comment]
Fixed in https://github.com/opensafely-core/sacro/pull/120
