### ISSUE TITLE
Record a comment describing the reason for release or rejection of the entire request

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#110]
The output checker needs to be able to record their assessment of the whole release request; for example when there are disclosivity concerns that span multiple outputs, or if significant changes are needed to the whole study before it can be released.

I'm open to suggestions about the UX here: whether there should be a comment field at the top of the UI, or there should be a button to enter a comment, or something else.

**Comment by bloodearnest** [comment]
Implementation notes:

Discussing with George and Tom O, we think think should be implemented as separate signal.  It may involve a modal popup or similar.


It could be added to the form submission data as single top level form encoded field.
