### ISSUE TITLE
Add version/build date

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sacro#122]
We currently hardcode the version as 0.1.0 in both sacro-app/package.json ~and pyoxidizer.bzl~ (only package.json matters currently).

We will want process/tooling to bump it. 

We should also find a way to include a build date, in the version or other metadata.

Ideally, we'd make this visible in the UI, possibly via a menu option.

**Comment by lucyb** [comment]
The display of the build date part of this ticket has been broken out into https://github.com/opensafely-core/sacro/issues/132

**Comment by madwort** [comment]
closing as duplicate of #132
