### ISSUE TITLE
Review electron app menu

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sacro#123]
We currently have the default electron app menu

There's lots of things there, and we may want to remove some: e.g. "Developer Tools"

We also may want to custom existing ones or add new ones. 

Some ideas that have been discussed

- view logs
- open different json file
- show version/build information
- detailed About dialog with links

**Comment by lucyb** [comment]
A customised About dialog, with the version information was added in this ticket https://github.com/opensafely-core/sacro/issues/132

Making the build date visible is covered in this ticket https://github.com/opensafely-core/sacro/issues/132

Opening a different file is covered in this PR https://github.com/opensafely-core/sacro/pull/144

**Comment by madwort** [comment]
covered in other tickets
