### ISSUE TITLE
Setup CI to build sacro app

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sacro#13]
We need to set up a CI process to build the sacro electron app

It will need to use parallel windows/linux runner. The windows runner should have everything we need to build it already installed according to the docs, except for just.

The output should be a app installer. It should be a CI artefact or a release of somekind.

Ideally we'd test it installs and maybe even runs?

We definitely want to do this post merge to main, but may also pre-merge?

We may also want to incorporate signing with this later on

**Comment by benbc** [comment]
@bloodearnest do you think we should extend the spike at this point to force ourselves to solve the multi-platform requirements.txt problem?

**Comment by bloodearnest** [comment]
So, I'm currently developing and testing CI just on windows.

We'll need to solve the requirements thing to support development/CI on linux too, but it could come after we've got windows based CI working?

**Comment by benbc** [comment]
Yup. Makes sense. I'll make a separate task.
