### ISSUE TITLE
Display multi-file outputs

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#138]
Some outputs, such as regressions, consist of more than one file. At the moment we just pick the first of those and ignore the rest. This issue changes that to display all of them.

There is no need to display the name of the files. We assume that the output checker can infer their purpose and relationship from the content.

The approach should work for custom outputs with combinations that we haven't seen before, rather than being restricted to just regressions. For example an image containing a chart alongside a CSV of the data for that chart should display usefully.

We should cope with multi-file outputs where we don't know how to render one of the files by rendering what we can and then displaying the [standard message](https://github.com/opensafely-core/sacro/issues/117) for those that we can't render.

A future issue will introduce the ability to open individual output files in an external application. It might be worth giving a bit of thought to where that will fit into the UI so that we don't have to rework things too much when we do that issue.

**Comment by benbc** [comment]
@bloodearnest Tom's PR is merged, so this is unblocked.

**Comment by bloodearnest** [comment]
Fixed in #176
