### ISSUE TITLE
Display a warning if the data has changed since the ACRO check was run

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#156]
ACRO produces a checksum for each output file. We should check the files we see against the checksums to ensure that they are the same. This allows us to guard against researchers accidentally changing files after they have been checked.

Note that this is not (and is not intended to be) tamper-proof. A malicious researcher could easily modify the checksum. It's a guard against mistaken error, not against attempts to subvert the output-checking process.

The checksums live in their own files in subdirectory. They could just as well live in the JSON, so we might consider parsing the files when we transform the JSON and including the checksums in our own transformed datastructure.

If the checksum verification fails, we should display a clear warning against the output so that the output checker can decide what to do.

**Comment by bloodearnest** [comment]
I've added a "checksum_valid" field to every file entry that can be used to display the message in #219
