### ISSUE TITLE
Display risk appetite

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#168]
ACRO can be parameterized according to the risk appetite of the TRE. The settings in operation when it runs are written to `config.json` in the outputs directory. We should display the settings (a series of name/value pairs) so the output checker can understand the intended risk appetite. These settings are quite verbose, so they should probably be in a collapsed element in the output detail pane.

**Comment by benbc** [comment]
There is a PR to take the new version of ACRO [here](https://github.com/opensafely-core/sacro/pull/194), which this should build on.

**Comment by lucyb** [comment]
This change isn't in v0.3.0 unfortunately

**Comment by bloodearnest** [comment]
I'm gonna do the first part of this, render the config to html in the page. @tomodwyer can add styling/UX

**Comment by bloodearnest** [comment]
https://github.com/opensafely-core/sacro/pull/214

**Comment by benbc** [comment]
Can we aim to get that PR merged with a preliminary Simon UI, then put Tom's enhancements into a separate PR (but still under this ticket, I guess)?

**Comment by bloodearnest** [comment]
We can, but its pretty ugly atm
