### ISSUE TITLE
Exception requests

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#191]
When researchers want to release an output that has failed its ACRO check, they need to make an explicit "exception request". We need to call out these exception requests in our UI.

The exception request is signalled by the presence of a new property on the output, introduced in this ACRO change: https://github.com/AI-SDC/ACRO/pull/112. The property contains a special comment that we should display.

I don't have any strong feelings about how this is displayed, except that we should make it clear what the purpose of the new comment is and use the terminology "exception request" somehow.

**Comment by bloodearnest** [comment]
This is in the output metadata as "exception" field.
