### ISSUE TITLE
Walking skeleton

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#22]
We'd like to build just enough of the system to prove that we can run end-to-end. In this case the upstream end is a set of study outputs and the downstream end is a zipfile release package containing those outputs and the ACRO reports on them.

We're only supporting simple, happy-path cases here. We should look for opportunities to shed scope from this walking skeleton where ever we can. But it is important that it's representative of the real end-to-end flow.

We will validate this flow with manual testing and the work for this issue includes producing a clear script for that manual testing so that it can be easily reproduced. There's no requirement to automate testing of the flow end-to-end, although of course the developers working on this issue should write any automated tests that they feel are appropriate (and build CI pipelines etc).

The flow here is:
1. Start with a pre-canned set of simple non-disclosive crosstab outputs
2. Run ACRO-runner against those outputs, producing a JSON report
3. Run standalone ACRO-viewer on Windows against those outputs and report
4. See “pass” indicator for each output in ACRO-viewer
5. Approve the outputs
6. Create zip containing outputs and ACRO reports

This issue is complete when:
- [ ] ACRO-viewer can be installed on Windows
- [ ] The above flow can be carried out
- [ ] A set of pre-canned outputs to use are available
- [ ] The steps to follow the flow are clearly documented

:trophy:  This will allow us to display an example of a crosstab output that has successfully passed the acro checks
:dart: We estimate that this should be done by 14-19th June

We have split out the work into their own issues:

- [x] https://github.com/opensafely-core/sacro/pull/31
- [x] https://github.com/opensafely-core/sacro/issues/50
- [x] https://github.com/opensafely-core/sacro/issues/44
- [x] https://github.com/opensafely-core/sacro/issues/45
- [x] https://github.com/opensafely-core/sacro/issues/48
- [x] https://github.com/opensafely-core/sacro/issues/49
- [x] https://github.com/opensafely-core/sacro/issues/46
- [x] https://github.com/opensafely-core/sacro/issues/47
- [x] https://github.com/opensafely-core/sacro/issues/53
- [x] https://github.com/opensafely-core/sacro/issues/82

**Comment by lucyb** [comment]
@bloodearnest to run through how the acro tool works

**Comment by tomodwyer** [comment]
- open a folder with the electron app
- display the files in a folder
- display the content of each file
- display the status of each file
- form to approve the content
  - generate a file with the approval (JSON? YAML? TXT?)
- create a zip
- electron download the ZIP? Place in folder?

**Comment by lucyb** [comment]
@bloodearnest to create a command to generate some outputs by running the acro-library, these will be put into a directory that the viewer will access

**Comment by lucyb** [comment]
We want to display an example of a crosstab output that has successfully passed the acro checks

* Use electron directory picker to choose initial directory
* Pass this to the python app and return list of files in that directory
* View contents of a CSV file (containing the crosstab) when clicked, formatted as a basic table
* Show the metadata of the corresponding file from the `results.json`, to show pass status, comments and name of output
* Clickable button to approve all outputs, which prompts the electron app to pass the list of outputs to the python app
* Python app takes the list of filenames and returns a zipfile
* The electron app prompts the user to save it to a location they specify and downloads the zip
