### ISSUE TITLE
Handle cell suppression failures

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#24]
When ACRO detects disclosivity risks in the outputs, those need to be flagged to the output checker and the outputs should not be released. There may be a variety of different failures possible, but here we deal with just one -- small numbers in crosstab outputs.

This issue is done when:
- [ ] A crosstab output with a small number failure is clearly indicated as a failure in the viewer
- [ ] The reason for the failure is displayed in the viewer
- [ ] The cells that contained small numbers are highlighted
- [ ] The output checker can still approve this output for release (this should be a no-op and is included for completeness)

Note that since we spiked this the format of the `output` field, which encodes the cell highlighting, has changed. It now has a rich JSON format rather than being CSV-in-a-string.

**Comment by lucyb** [comment]
This needs further refinement before it's ready to work on. Catherine's story map may provide more information

**Comment by lucyb** [comment]
From @benbc 

I think the outstanding questions are:
1. Should it be possible to release output that have failed? (The PID is ambiguous.)
2. If it's not possible to release this failed output, does that mean there can be no release at all? (The partial release question again.)

**Comment by benbc** [comment]
Resolution of the outstanding questions:

1. Yes, it should be possible to release failed outputs. Note that _in this issue_ we just handle that by displaying the failed outputs and allowing the researcher to carry on approving the whole set for release. Individual output approval will come in a later issue.
2. Partial outputs are allowed. Again, this will come later -- for this issue it continues to be all-or-nothing.

**Comment by benbc** [comment]
@lucyb I think this is now ready to go.
