### ISSUE TITLE
Package ACRO-viewer for Linux desktop

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#25]
Some TREs use Linux instead of Windows. We need to provide a similar installation and GUI experience for them.

Some investigation is needed to determine what kind of packaging would be most useful. Please start by getting in touch with TREs who use Linux to find out what they could support.

**Comment by lucyb** [comment]
Can this issue be closed? We've since spoken with TREs and it looks like Windows is the way to go.

**Comment by benbc** [comment]
We may still want this, but there's no reason to have the issue lying around -- we can always create a new one.
