### ISSUE TITLE
Try out the Windows installer in TPP

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#26]
Get hold of someone at TPP who has permission to install packages on the L4 server and ask them to try the spike.

**Comment by lucyb** [comment]
@bloodearnest to put the installer on TPP and then I'll try installing it (or getting TPP to do it)

**Comment by lucyb** [comment]
I've attempted to install this myself on L4. I received the message "The publisher of SACRO-0.1.0.msi couldn't be verified.", but was able to start to run the installer anyway. Unsurprisingly, I then received the message "The system administrator has set policies to prevent this installation." and was unable to proceed.

**Comment by lucyb** [comment]
TPP have responded to say that they're going to raise it in their next team meeting and will get back to us in a couple of weeks.

**Comment by lucyb** [comment]
This was installed today without issue. Empty audit and error logs are present in c:\Windows\System32\SACRO.
