### ISSUE TITLE
Hello-world app installed in TRE

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sacro#68]
>**Note**: This issue should be moved into the SACRO repo once we have one

❗ Deadline is end of May

The goal is to have a very basic "hello world" app installed within a TRE by the deadline.

Having this installed within a TRE will allow us to test our assumptions about what's available within the target TRE environments and what's permitted. It will allow us to make a decision about what approach to use for packaging and installing the standalone output-viewer.

We should do a time-boxed evaluation (spike) of several possible options. These are provided in more detail [in this doc](https://docs.google.com/document/d/1s8UpQUOdLAM40VJ2HunjAL_xrsd0oo6gCPflqanjdkE/edit#heading=h.bln4uk18adwq) and they likely to be:

- [ ] Pip installable package

- [ ] PyOxidizer

- [ ] PyInstaller

- [ ] Electron (given that we expect the backend to be Python, this not be worth investigating right now) (see [earlier spike](https://github.com/opensafely-core/spike-sacro-electron))

It is reasonable to assume that the target TRE environments are running Windows, with Python 3.10 and the Edge/Chrome browser available.

We should provide the TREs with a link to a GitHub release, which could be a zip file, .exe or .msi.

**Comment by benbc** [comment]
We're giving up on getting the hello world app installed. We'll have the real app to try soon.
