### ISSUE TITLE
Selective release and rejection of outputs

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#73]
Output checkers need to be able to approve a subset of outputs for release. Outputs that are not to be released will be "rejected".

This issue introduces selection of individual outputs for approval and rejection. It does not include JSON metadata describing the rejection, that will follow in a later issue.

This issue is complete when:

- [ ] The output checker can individually select "approve" or "reject" for each output.
- [ ] The "Approve and download" button is renamed to "Release and download".
- [ ] It's not possible to click the "Release and download" button until each output has been explicitly approved or rejected.
- [ ] The output checker gets sufficient feedback from the UI that they understand why they can't click the "Release and download" button.
- [ ] It's possible for the output checker to change their mind about an output after they select "approve" or "reject" (including resetting to the initial null state).
- [x] The zipfile downloaded contains all approved outputs and no rejected outputs.
- [x] If all outputs are rejected then it's not possible to click the "Release and download" button (and feedback is given so the output checker understands why).

**Comment by lucyb** [comment]
Note: The current endpoint needs to be updated to take a list of files for release

**Comment by bloodearnest** [comment]
Doing some preliminary work on this.

**Comment by bloodearnest** [comment]
I've currently implemented this as just an "Approve" button, as rejection w/out comments is just not clicking that.

We could add a reject button, but it would do nothing when clicked currently.

I propose that we add a reject button when we add the ability to comment on why it was rejected?

**Comment by bloodearnest** [comment]
> The output checker gets sufficient feedback from the UI that they understand why they can't click the "Release and download" button.

The current styling that was already in place greys out the box and changes the cursor to a no entry sign.  Is that sufficient?

Perhaps some of the styling parts could be split off into a separate ticket for Tom?

**Comment by benbc** [comment]
I think it's important for the output checker to understand _why_ they can't release, otherwise the feedback that the UI is giving them isn't actionable.

**Comment by benbc** [comment]
I think it would be good to make rejection an explicit action, to help guide the output checker through checking _all_ the outputs.
