### ISSUE TITLE
Generate an audit trail of workflow decisions

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sacro#83]
Generate an audit trail of workflow decisions produced from the acro-viewer. Initially this may just be when the files were approved and who by.

For this initial implementation, we should place the information into a log file within the user's local AppData directory. In future, we could use the Windows application event log for this or some other independent log that's not editable by users.

This issue will be done when:
- [ ] A log file is produced containing a list of all files in the request, whether they were approved or rejected, when they were approved and who by

Recording of the reason for the approve/reject decision will be handled in a future issue.

Dependent on: https://github.com/opensafely-core/sacro/issues/73

**Comment by benbc** [comment]
@lucyb How do you think we should determine who the researcher is? Have them enter their name? use their Windows username?

**Comment by lucyb** [comment]
It should be possible to get this from within the [electron app](https://stackoverflow.com/a/46318558). If that doesn't work for any reason, we might have to fallback to asking them to enter their name, but hopefully we can avoid that.

**Comment by bloodearnest** [comment]
We can get the windows username via python app and log the actions (or the electron app, but it's python that will be maintaining the log I think?)
