### ISSUE TITLE
Display researcher comments

### ISSUE THREAD

**Issue by benbc** [opensafely-core/sacro#86]
Researchers can pass on comments to the output checkers. These are included in the ACRO JSON file in the `comments` field for each output. These comments are used to explain why the researchers believe that the output should be released; they may be included for outputs that fail the ACRO check to explain why the failure is a false positive, or for passing outputs when the researcher thinks that the output checker may believe that the result is a false negative.

This issue is complete when:

- [ ] For each output that has a comment in the JSON, that comment is displayed in the viewer.
- [ ] Outputs without comments are still displayed nicely.
- [ ] There is no change to the approval process.

**Comment by tomodwyer** [comment]
Work completed as part of #74

## With comments

<img width="866" alt="CleanShot 2023-06-21 at 14 05 19@2x" src="https://github.com/opensafely-core/sacro/assets/24863179/48e4ba8c-8502-44f1-946f-ba22d504e64b">

## No comments

<img width="871" alt="CleanShot 2023-06-21 at 14 05 27@2x" src="https://github.com/opensafely-core/sacro/assets/24863179/ef93e427-e0b0-49b6-9381-841332ddb322">
